

title: "Tetretalk is Down for maintanence and upgrades, please check back again later!"
description: "Tetretalk Is offline!"
locale: en
author: 

countdown:
  theme: red
  year: 2018
  month: 8
  day: 28
  hour: 16
  minute: 0


owner:
  name:
  email:
  twitter:
  google-plus:
  instagramm:
  aboutlink:
    url:
    caption:


# Important Stuff - don't mess with please
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
